services:
  app:
    container_name: python
    build:
      context: ./docker/python
    volumes:
      - .:/app
    ports:
      - 8000:8000
    stdin_open: true
    tty: true

  jupyter:
    container_name: jupyter-py
    build:
      context: ./docker/jupyter
    ports:
      - 8888:8888
    volumes:
      - .:/app
